a = imread('peppers.bmp');
a = imresize(a,[256 256]);
b = imnoise(a,'Salt & pepper',0.1);
imwrite(b,'peppers10noise.bmp');
b = imnoise(a,'Salt & pepper',0.3);
imwrite(b,'peppers30noise.bmp');
b = imnoise(a,'Salt & pepper',0.5);
imwrite(b,'peppers50noise.bmp');
b = imnoise(a,'Salt & pepper',0.7);
imwrite(b,'peppers70noise.bmp');
b = imnoise(a,'Salt & pepper',0.9);
imwrite(b,'peppers90noise.bmp');
