PHONY: all
all:
	doxygen Fastflow_doxygen
	@echo
	@echo "*****************************************************"
	@echo "Look for the generated documents in the doc directory"
	@echo "*****************************************************"
	@echo
