swps3: dblen.c File Reference
dblen.c File Reference
#include "fasta.h"
#include <stdio.h>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 5 of file dblen.c.
References swps3_closeLib(), swps3_getSequenceName(), swps3_openLib(), and swps3_readNextSequence().