swps3: debug.h File Reference
debug.h File Reference
Routines for error reporting.
Defines
#define debug(...)
Functions
void error (const char *str,...)
printf-like function for critical error reporting.
void warning (const char *str,...)
printf-like function for noncritical error reporting.
Detailed Description
Routines for error reporting.
Definition in file debug.h.
Define Documentation
#define debug (...)
Definition at line 39 of file debug.h.
Referenced by swps3_alignmentByteSSE(), and swps3_createProfileByteSSE().
Function Documentation
void error (const char * str, ...)
printf-like function for critical error reporting.
Reports a message to stderr and terminates the program.
Parameters:
str A format string.
Definition at line 40 of file debug.c.
Referenced by swps3_openLib(), swps3_readDMatrix(), swps3_readNextSequence(), swps3_readSBMatrix(), and swps3_translateSequence().
void warning (const char * str, ...)
printf-like function for noncritical error reporting.
Reports a message to stderr without terminating the program.
Parameters:
str A format string.
Definition at line 56 of file debug.c.
Referenced by swps3_readNextSequence().