swps3: DynProgr_altivec.h File Reference
DynProgr_altivec.h File Reference
Profile generation and alignment on IBM Altivec^TM instruction set.
#include "swps3.h"
Functions
void * swps3_createProfileByteAltivec (const char *query, int queryLen, SBMatrix matrix)
C version for allocation and computation of a 8-bit integer profile for the given data type and similarity matrix.
void * swps3_createProfileFloatAltivec (const char *query, int queryLen, SBMatrix matrix)
C version for allocation and computation of a 32-bit floating point profile for the given data type and similarity matrix.
void * swps3_createProfileShortAltivec (const char *query, int queryLen, SBMatrix matrix)
C version for allocation and computation of a 16-bit integer profile for the given data type and similarity matrix.
double swps3_dynProgrByteAltivec (const char *db, int dbLen, void *profile, Options *options)
C version of alignment routine for Altivec for signed 8-bit integers.
double swps3_dynProgrFloatAltivec (const char *db, int dbLen, void *profile, Options *options)
C version of alignment routine for Altivec for signed 32-bit floating point values.
double swps3_dynProgrShortAltivec (const char *db, int dbLen, void *profile, Options *options)
C version of alignment routine for Altivec for signed 16-bit integers.
Detailed Description
Profile generation and alignment on IBM Altivec^TM instruction set.
Definition in file DynProgr_altivec.h.
Function Documentation
void* swps3_createProfileByteAltivec (const char * query, int queryLen, SBMatrix matrix)
C version for allocation and computation of a 8-bit integer profile for the given data type and similarity matrix.
Parameters:
query The query sequence.
queryLen The length of the query sequence.
matrix The similarity matrix.
Returns:
An initialized profile data structure.
Definition at line 774 of file DynProgr_altivec.cc.
Referenced by main().
void* swps3_createProfileFloatAltivec (const char * query, int queryLen, SBMatrix matrix)
C version for allocation and computation of a 32-bit floating point profile for the given data type and similarity matrix.
Parameters:
query The query sequence.
queryLen The length of the query sequence.
matrix The similarity matrix.
Returns:
An initialized profile data structure.
Definition at line 804 of file DynProgr_altivec.cc.
Referenced by main().
void* swps3_createProfileShortAltivec (const char * query, int queryLen, SBMatrix matrix)
C version for allocation and computation of a 16-bit integer profile for the given data type and similarity matrix.
Parameters:
query The query sequence.
queryLen The length of the query sequence.
matrix The similarity matrix.
Returns:
An initialized profile data structure.
Definition at line 789 of file DynProgr_altivec.cc.
Referenced by main().
double swps3_dynProgrByteAltivec (const char * db, int dbLen, void * profile, Options * options)
C version of alignment routine for Altivec for signed 8-bit integers.
Parameters:
db The database sequence.
dbLen The length of the database sequence.
profile A profile data structure previously computed from the query sequence.
options Some global options.
Returns:
The local alignment score or DBL_MAX if score exceeds threshold.
See also:
swps3_createProfileByteAltivec()
swps3_dynProgrAltivec()
Definition at line 718 of file DynProgr_altivec.cc.
Referenced by main().
double swps3_dynProgrFloatAltivec (const char * db, int dbLen, void * profile, Options * options)
C version of alignment routine for Altivec for signed 32-bit floating point values.
Parameters:
db The database sequence.
dbLen The length of the database sequence.
profile A profile data structure previously computed from the query sequence.
options Some global options.
Returns:
The local alignment score or DBL_MAX if score exceeds threshold.
See also:
swps3_createProfileFloatAltivec()
swps3_dynProgrAltivec()
Definition at line 759 of file DynProgr_altivec.cc.
Referenced by main().
double swps3_dynProgrShortAltivec (const char * db, int dbLen, void * profile, Options * options)
C version of alignment routine for Altivec for signed 16-bit integers.
Parameters:
db The database sequence.
dbLen The length of the database sequence.
profile A profile data structure previously computed from the query sequence.
options Some global options.
Returns:
The local alignment score or DBL_MAX if score exceeds threshold.
See also:
swps3_createProfileShortAltivec()
swps3_dynProgrAltivec()
Definition at line 738 of file DynProgr_altivec.cc.
Referenced by main().