swps3: matrix.c File Reference
matrix.c File Reference
Routines for reading matrix files and converting matrices.
#include "swps3.h"
#include "matrix.h"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "debug.h"
#include <sys/types.h>
#include <math.h>
Functions
static char * skip (char *line)
EXPORT SBMatrix swps3_convertMatrixD2B (double factor)
EXPORT double swps3_factorFromThreshold (double threshold, double singleGapCost)
EXPORT DMatrix swps3_readDMatrix (char *filename)
EXPORT SBMatrix swps3_readSBMatrix (char *filename)
Variables
static int8_t sbmatrix[MATRIX_DIM][MATRIX_DIM] __ALIGNED__
Detailed Description
Routines for reading matrix files and converting matrices.
Definition in file matrix.c.
Function Documentation
static char* skip (char * line) [static]
Definition at line 40 of file matrix.c.
Referenced by swps3_readDMatrix(), and swps3_readSBMatrix().
EXPORT SBMatrix swps3_convertMatrixD2B (double factor)
Definition at line 146 of file matrix.c.
References MATRIX_DIM.
EXPORT double swps3_factorFromThreshold (double threshold, double singleGapCost)
Definition at line 160 of file matrix.c.
EXPORT DMatrix swps3_readDMatrix (char * filename)
Definition at line 48 of file matrix.c.
References error(), and skip().
EXPORT SBMatrix swps3_readSBMatrix (char * filename)
Definition at line 97 of file matrix.c.
References error(), and skip().
Referenced by main().
Variable Documentation
double dmatrix [MATRIX_DIM][MATRIX_DIM] __ALIGNED__ [static]
Definition at line 45 of file matrix.c.