swps3: matrix.h File Reference
matrix.h File Reference
Routines for reading matrix files and converting matrices.
#include "swps3.h"
#include <sys/types.h>
Typedefs
typedef double * DMatrix
typedef int8_t * SBMatrix
Functions
SBMatrix swps3_convertMatrixD2SB (double factor)
double swps3_factorFromThreshold (double threshold, double singleGapCost)
DMatrix swps3_readDMatrix (char *filename)
SBMatrix swps3_readSBMatrix (char *filename)
Detailed Description
Routines for reading matrix files and converting matrices.
Definition in file matrix.h.
Typedef Documentation
typedef double* DMatrix
Definition at line 37 of file matrix.h.
typedef int8_t* SBMatrix
Definition at line 36 of file matrix.h.
Function Documentation
SBMatrix swps3_convertMatrixD2SB (double factor)
double swps3_factorFromThreshold (double threshold, double singleGapCost)
Definition at line 160 of file matrix.c.
DMatrix swps3_readDMatrix (char * filename)
Definition at line 48 of file matrix.c.
References error(), and skip().
SBMatrix swps3_readSBMatrix (char * filename)
Definition at line 97 of file matrix.c.
References error(), and skip().
Referenced by main().