swps3: swps3.c File Reference
swps3.c File Reference
Main procedure and multi-threading code.
#include "swps3.h"
#include "matrix.h"
#include "fasta.h"
#include "DynProgr_scalar.h"
#include "DynProgr_sse_byte.h"
#include "DynProgr_sse_short.h"
#include "DynProgr_PPU.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/select.h>
#include <unistd.h>
#include <string.h>
#include <assert.h>
#include <float.h>
Functions
int main (int argc, char *argv[])
static ssize_t read_all (int fd, void *buf, size_t len)
static ssize_t write_all (int fd, const void *data, size_t len)
Detailed Description
Main procedure and multi-threading code.
Definition in file swps3.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 88 of file swps3.c.
References __ALIGNED__, ALTIVEC, Options::gapExt, Options::gapOpen, MATRIX_DIM, MAX_SEQ_LENGTH, MAX_SEQ_NAME_LENGTH, PS3, read_all(), SCALAR, SSE2, swps3_alignmentByteSPE(), swps3_alignmentByteSSE(), swps3_alignmentProfileSPE(), swps3_alignmentShortSPE(), swps3_alignmentShortSSE(), swps3_alignScalar(), swps3_closeLib(), swps3_createProfileByteAltivec(), swps3_createProfileBytePPU(), swps3_createProfileByteSSE(), swps3_createProfileFloatAltivec(), swps3_createProfileFloatPPU(), swps3_createProfileShortAltivec(), swps3_createProfileShortPPU(), swps3_createProfileShortSSE(), swps3_dynProgrByteAltivec(), swps3_dynProgrFloatAltivec(), swps3_dynProgrShortAltivec(), swps3_freeProfileByteSSE(), swps3_freeProfilePPU(), swps3_freeProfileShortSSE(), swps3_getSequenceName(), swps3_loadProfileByte(), swps3_loadProfileShort(), swps3_openLib(), swps3_readNextSequence(), swps3_readSBMatrix(), Options::threshold, and write_all().
static ssize_t read_all (int fd, void * buf, size_t len) [static]
Definition at line 71 of file swps3.c.
Referenced by main().
static ssize_t write_all (int fd, const void * data, size_t len) [static]
Definition at line 54 of file swps3.c.
Referenced by main().